version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=password
    volumes:
      - ./db:/var/lib/mysql
    container_name: db
  php:
    build:
      context: ./build/php
    container_name: php
    volumes:
      - ./:/home/ee-replication
    working_dir: /home/ee-replication
    links:
      - db